spring:
  profiles: dev

config:
  mqttsvr.url: test.mosquitto.org
  mqttsvr.port: 1883
  mqttsvr.timeout: 5000
  mqttsvr.topicId: 6cb48084-fcd9-486e-98ed-a96c56fcafe5
  mqttsvr.inboundTopic: BRE/calculateWinterSupplementInput/
  mqttsvr.outboundTopic: BRE/calculateWinterSupplementOutput/
  
server:
  port: 8082